### PR TITLE
Update SECURITY.md

### PR DESCRIPTION
**Pull request by JustinCappos**
Spelling fixes.  There may be other ones I didn't spot.

### CODE REVIEW

**Review by FeynmanZhou — APPROVED** [review]
Thanks @JustinCappos . LGTM

**Review by priteshbandi — APPROVED** [review]
LGTM

**Review by yizha1 — APPROVED** [review]
Thanks @JustinCappos, LGTM

**Review by toddysm — COMMENTED** [review]
LGTM

**Pull request merged**
